version: "3.8"

services:
  echo-bot:
    build:
      context: .
      target: dev
    expose:
      - "3978"
    ports:
      - "3978:3978"
    # env_file:
    #   - .env.local
    environment:
      HOST: 0.0.0.0
