version: "3.8"

services:
  echo-bot:
    build:
      context: .
      target: dev

    # Linux Only?
    # SEE: https://stackoverflow.com/a/75233758/1361858
    # network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    expose:
      - "${PORT}"

    ports:
      - "${PORT}:${PORT}"

    env_file:
      - .env
      # - .env.docker
      # - .env.local
