version: "3.8"

services:
  echo-bot:
    build:
      context: .
      target: dev
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    # env_file:
    #   - .env.docker
    environment:
      HOST: "${HOST}"
