#!/bin/bash

set -e
set -v


docker tag ${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_TAG} ${CONTAINER_REGISTRY_URL}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_TAG}
docker tag ${CONTAINER_IMAGE_NAME}.dev:${CONTAINER_IMAGE_TAG} ${CONTAINER_REGISTRY_URL}/${CONTAINER_IMAGE_NAME}.dev:${CONTAINER_IMAGE_TAG}

docker push ${CONTAINER_REGISTRY_URL}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_TAG}
docker push ${CONTAINER_REGISTRY_URL}/${CONTAINER_IMAGE_NAME}.dev:${CONTAINER_IMAGE_TAG}

set +v
set +e
